#!/bin/bash
# Complete Fix for Forbidden Resource Error
# This script will fully reset your session and test the fix

echo "================================================"
echo "   MAXWEALTH - Complete Forbidden Fix Guide"
echo "================================================"
echo ""
echo "✓ What we've done:"
echo "  1. Fixed RolesGuard in backend"
echo "  2. Updated your user role to Admin in database"
echo "  3. Restarted both servers"
echo ""
echo "✗ What's blocking you:"
echo "  - Your browser still has OLD token from before role change"
echo "  - Need to clear cache and log in again"
echo ""
echo "================================================"
echo "   Follow These Exact Steps:"
echo "================================================"
echo ""
echo "STEP 1: Clear Browser Storage"
echo "  1. Press F12 to open Developer Tools"
echo "  2. Go to 'Application' or 'Storage' tab"
echo "  3. Click 'Local Storage'"
echo "  4. Click on 'http://localhost:3001'"
echo "  5. Select all and delete everything"
echo ""
echo "STEP 2: Clear Cookies"
echo "  1. Still in Storage tab"
echo "  2. Click 'Cookies'"
echo "  3. Click 'http://localhost:3001'"
echo "  4. Delete all cookies"
echo ""
echo "STEP 3: Hard Refresh Browser"
echo "  Press Ctrl+Shift+R (Windows/Linux) or Cmd+Shift+R (Mac)"
echo ""
echo "STEP 4: Close Browser"
echo "  1. Close ALL tabs"
echo "  2. Close the entire browser"
echo "  3. Wait 5 seconds"
echo ""
echo "STEP 5: Reopen & Log In"
echo "  1. Open browser"
echo "  2. Go to: http://localhost:3001"
echo "  3. Enter phone: 7306100556"
echo "  4. Enter OTP (check SMS or backend logs)"
echo "  5. Click Login"
echo ""
echo "STEP 6: Test Create"
echo "  1. Go to Admin Dashboard → Allocations"
echo "  2. Click Create button"
echo "  3. Enter Name: 'Test Portfolio'"
echo "  4. Enter Description: 'Testing'"
echo "  5. Click Create"
echo ""
echo "✓ EXPECTED RESULT:"
echo "  - Form submits"
echo "  - Success message"
echo "  - New allocation appears in list"
echo ""
echo "================================================"
echo ""
