import { MigrationInterface, QueryRunner } from 'typeorm';

export class SignzyMastersMigration1720965715027 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE countries (
            id INT AUTO_INCREMENT PRIMARY KEY,
            country VARCHAR(100),
            code VARCHAR(50)
        );`);

    await queryRunner.query(`INSERT INTO countries (country, code) VALUES
            ('India', '101'),
            ('Albania', '003'),
            ('Aland Islands', '002'),
            ('Afghanistan', '001'),
            ('Algeria', '004'),
            ('American Samoa', '005'),
            ('Andorra', '006'),
            ('Angola', '007'),
            ('Anguilla', '008'),
            ('Antarctica', '009'),
            ('Antigua And Barbuda', '010'),
            ('Argentina', '011'),
            ('Armenia', '012'),
            ('Aruba', '013'),
            ('Australia', '014'),
            ('Austria', '015'),
            ('Azerbaijan', '016'),
            ('Bahamas', '017'),
            ('Bahrain', '018'),
            ('Bangladesh', '019'),
            ('Barbados', '020'),
            ('Belarus', '021'),
            ('Belgium', '022'),
            ('Belize', '023'),
            ('Benin', '024'),
            ('Bermuda', '025'),
            ('Bhutan', '026'),
            ('Bolivia', '027'),
            ('Bosnia And Herzegovina', '028'),
            ('Botswana', '029'),
            ('Bouvet Island', '030'),
            ('Brazil', '031'),
            ('British Indian Ocean Territory', '032'),
            ('Brunei Darussalam', '033'),
            ('Bulgaria', '034'),
            ('Burkina Faso', '035'),
            ('Burundi', '036'),
            ('Cambodia', '037'),
            ('Cameroon', '038'),
            ('Canada', '039'),
            ('Cape Verde', '040'),
            ('Cayman Islands', '041'),
            ('Central African Republic', '042'),
            ('Chad', '043'),
            ('Chile', '044'),
            ('China', '045'),
            ('Christmas Island', '046'),
            ('Cocos (Keeling) Islands', '047'),
            ('Colombia', '048'),
            ('Comoros', '049'),
            ('Congo', '050'),
            ('Congo, The Democratic Republic Of The', '051'),
            ('Cook Islands', '052'),
            ('Costa Rica', '053'),
            ("Cote DIvoire", '054'),
            ('Croatia', '055'),
            ('Cuba', '056'),
            ('Cyprus', '057'),
            ('Czech Republic', '058'),
            ('Denmark', '059'),
            ('Djibouti', '060'),
            ('Dominica', '061'),
            ('Dominican Republic', '062'),
            ('Ecuador', '063'),
            ('Egypt', '064'),
            ('El Salvador', '065'),
            ('Equatorial Guinea', '066'),
            ('Eritrea', '067'),
            ('Estonia', '068'),
            ('Ethiopia', '069'),
            ('Falkland Islands (Malvinas)', '070'),
            ('Faroe Islands', '071'),
            ('Fiji', '072'),
            ('Finland', '073'),
            ('France', '074'),
            ('French Guiana', '075'),
            ('French Polynesia', '076'),
            ('French Southern Territories', '077'),
            ('Gabon', '078'),
            ('Gambia', '079'),
            ('Georgia', '080'),
            ('Germany', '081'),
            ('Ghana', '082'),
            ('Gibraltar', '083'),
            ('Greece', '084'),
            ('Greenland', '085'),
            ('Grenada', '086'),
            ('Guadeloupe', '087'),
            ('Guam', '088'),
            ('Guatemala', '089'),
            ('Guernsey', '090'),
            ('Guinea', '091'),
            ('Guinea-Bissau', '092'),
            ('Guyana', '093'),
            ('Haiti', '094'),
            ('Heard Island And Mcdonald Islands', '095'),
            ('Holy See (Vatican City State)', '096'),
            ('Honduras', '097'),
            ('Hong Kong', '098'),
            ('Hungary', '099'),
            ('Iceland', '100'),
            ('Indonesia', '102'),
            ('Iran, Islamic Republic Of', '103'),
            ('Iraq', '104'),
            ('Ireland', '105'),
            ('Isle Of Man', '106'),
            ('Israel', '107'),
            ('Italy', '108'),
            ('Jamaica', '109'),
            ('Japan', '110'),
            ('Jersey', '111'),
            ('Jordan', '112'),
            ('Kazakhstan', '113'),
            ('Kenya', '114'),
            ('Kiribati', '115'),
            ('Korea, Democratic Peoples Republic Of', '116'),
            ('Korea, Republic Of', '117'),
            ('Kuwait', '118'),
            ('Kyrgyzstan', '119'),
            ('Lao Peoples Democratic Republic', '120'),
            ('Latvia', '121'),
            ('Lebanon', '122'),
            ('Lesotho', '123'),
            ('Liberia', '124'),
            ('Libyan Arab Jamahiriya', '125'),
            ('Liechtenstein', '126'),
            ('Lithuania', '127'),
            ('Luxembourg', '128'),
            ('Macao', '129'),
            ('Macedonia, The Former Yugoslav Republic Of', '130'),
            ('Madagascar', '131'),
            ('Malawi', '132'),
            ('Malaysia', '133'),
            ('Maldives', '134'),
            ('Mali', '135'),
            ('Malta', '136'),
            ('Marshall Islands', '137'),
            ('Martinique', '138'),
            ('Mauritania', '139'),
            ('Mauritius', '140'),
            ('Mayotte', '141'),
            ('Mexico', '142'),
            ('Micronesia, Federated States Of', '143'),
            ('Moldova, Republic Of', '144'),
            ('Monaco', '145'),
            ('Mongolia', '146'),
            ('Montserrat', '147'),
            ('Morocco', '148'),
            ('Mozambique', '149'),
            ('Myanmar', '150'),
            ('Namibia', '151'),
            ('Nauru', '152'),
            ('Nepal', '153'),
            ('Netherlands', '154'),
            ('Netherlands Antilles', '155'),
            ('New Caledonia', '156'),
            ('New Zealand', '157'),
            ('Nicaragua', '158'),
            ('Niger', '159'),
            ('Nigeria', '160'),
            ('Niue', '161'),
            ('Norfolk Island', '162'),
            ('Northern Mariana Islands', '163'),
            ('Norway', '164'),
            ('Oman', '165'),
            ('Pakistan', '166'),
            ('Palau', '167'),
            ('Palestinian Territory, Occupied', '168'),
            ('Panama', '169'),
            ('Papua New Guinea', '170'),
            ('Paraguay', '171'),
            ('Peru', '172'),
            ('Philippines', '173'),
            ('Pitcairn', '174'),
            ('Poland', '175'),
            ('Portugal', '176'),
            ('Puerto Rico', '177'),
            ('Qatar', '178'),
            ('Reunion', '179'),
            ('Romania', '180'),
            ('Russian Federation', '181'),
            ('Rwanda', '182'),
            ('Saint Helena', '183'),
            ('Saint Kitts And Nevis', '184'),
            ('Saint Lucia', '185'),
            ('Saint Pierre And Miquelon', '186'),
            ('Saint Vincent And The Grenadines', '187'),
            ('Samoa', '188'),
            ('San Marino', '189'),
            ('Sao Tome And Principe', '190'),
            ('Saudi Arabia', '191'),
            ('Senegal', '192'),
            ('Serbia And Montenegro', '193'),
            ('Seychelles', '194'),
            ('Sierra Leone', '195'),
            ('Singapore', '196'),
            ('Slovakia', '197'),
            ('Slovenia', '198'),
            ('Solomon Islands', '199'),
            ('Somalia', '200'),
            ('South Africa', '201'),
            ('South Georgia And The South Sandwich Islands', '202'),
            ('Spain', '203'),
            ('Sri Lanka', '204'),
            ('Sudan', '205'),
            ('Suriname', '206'),
            ('Svalbard And Jan Mayen', '207'),
            ('Swaziland', '208'),
            ('Sweden', '209'),
            ('Switzerland', '210'),
            ('Syrian Arab Republic', '211'),
            ('Taiwan, Province Of China', '212'),
            ('Tajikistan', '213'),
            ('Tanzania, United Republic Of', '214'),
            ('Thailand', '215'),
            ('Timor-Leste', '216'),
            ('Togo', '217'),
            ('Tokelau', '218'),
            ('Tonga', '219'),
            ('Trinidad And Tobago', '220'),
            ('Tunisia', '221'),
            ('Turkey', '222'),
            ('Turkmenistan', '223'),
            ('Turks And Caicos Islands', '224'),
            ('Tuvalu', '225'),
            ('Uganda', '226'),
            ('Ukraine', '227'),
            ('United Arab Emirates', '228'),
            ('United Kingdom', '229'),
            ('United States', '230'),
            ('United States Minor Outlying Islands', '231'),
            ('Uruguay', '232'),
            ('Uzbekistan', '233'),
            ('Vanuatu', '234'),
            ('Venezuela', '235'),
            ('Viet Nam', '236'),
            ('Virgin Islands, British', '237'),
            ('Virgin Islands, U.S.', '238'),
            ('Wallis And Futuna', '239'),
            ('Western Sahara', '240'),
            ('Yemen', '241'),
            ('Zambia', '242'),
            ('Zimbabwe', '243'),
            ('Cote Divoire', 'CI'),
            ('Korea, Democratic Peoples Republic Of', 'KP'),
            ('Lao Peoples Democratic Republic', '120');
        `);

    await queryRunner.query(`CREATE TABLE state_and_codes (
            id INT AUTO_INCREMENT PRIMARY KEY,
            state VARCHAR(100),
            cams_code VARCHAR(50),
            voters_code VARCHAR(50)
        );`);

    await queryRunner.query(`INSERT INTO state_and_codes (state, cams_code, voters_code) VALUES
            ('Andaman & Nicobar', 'AN', 'Andaman and Nicobar Islands'),
            ('Andhra Pradesh', 'AP', 'Andhra Pradesh'),
            ('Arunachal Pradesh', 'AR', 'ArunachalPradesh'),
            ('Assam', 'AS', 'Assam'),
            ('Bihar', 'BR', 'Bihar'),
            ('Chandigarh', 'CH', 'Chandigarh'),
            ('Chattisgarh', 'CG', 'Chhattisgarh'),
            ('Dadra and Nagar Haveli', 'DN', 'DadraandNagar'),
            ('Daman & Diu', 'DD', 'Diu-Daman'),
            ('Delhi', 'DL', 'Delhi'),
            ('Goa', 'GA', 'Goa'),
            ('Gujarat', 'GJ', 'Gujarat'),
            ('Haryana', 'HR', 'Haryana'),
            ('Himachal Pradesh', 'HP', 'HimachalPradesh'),
            ('Jammu & Kashmir', 'JK', 'JammuKashmir'),
            ('Jharkhand', 'JH', 'Jharkhand'),
            ('Karnataka', 'KA', 'Karnataka'),
            ('Kerala', 'KL', 'Kerala'),
            ('Lakshadweep', 'LD', 'Lakshadweep'),
            ('Madhya Pradesh', 'MP', 'Madhya Pradesh'),
            ('Maharashtra', 'MH', 'Maharashtra'),
            ('Manipur', 'MN', 'Manipur'),
            ('Meghalaya', 'ML', 'Meghalaya'),
            ('Mizoram', 'MZ', 'Mizoram'),
            ('Nagaland', 'NL', 'Nagaland'),
            ('Odisha', 'OR', 'Odisha'),
            ('Pondicherry', 'PY', 'Puducherry'),
            ('Punjab', 'PB', 'Punjab'),
            ('Rajasthan', 'RJ', 'Rajasthan'),
            ('Sikkim', 'SK', 'Sikkim'),
            ('Tamil Nadu', 'TN', 'TamilNadu'),
            ('Telangana', 'TS', 'Telangana'),
            ('Tripura', 'TR', 'Tripura'),
            ('Uttar Pradesh', 'UP', 'Uttar Pradesh'),
            ('Uttarakhand', 'UA', 'Uttarakhand'),
            ('West Bengal', 'WB', 'West Bengal'),
            ('Other', 'XX', NULL);`);

    await queryRunner.query(`CREATE TABLE occupations (
                id INT AUTO_INCREMENT PRIMARY KEY,
                code VARCHAR(10),
                occupation_description VARCHAR(100),
                occupation_identifier VARCHAR(100)
            );
            `);

    await queryRunner.query(`INSERT INTO occupations (code, occupation_description,occupation_identifier) VALUES
                        ('01', 'Private Sector','private_sector'),
                        ('02', 'Public Sector','public_sector'),
                        ('03', 'Business','business'),
                        ('04', 'Professional','professional'),
                        ('06', 'Retired','retired'),
                        ('07', 'Housewife','housewife'),
                        ('08', 'Student','student'),
                        ('10', 'Government Sector','government_sector'),
                        ('99', 'Others','others'),
                        ('11', 'Self Employed','self_employed'),
                        ('12', 'Not Categorized','not_categorized');
            `);

    await queryRunner.query(`
            CREATE TABLE kyc_account_types (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    kyc_acc_code VARCHAR(10),
                    kyc_acc_description VARCHAR(100)
                );
            `);

    await queryRunner.query(`INSERT INTO kyc_account_types (kyc_acc_code, kyc_acc_description) VALUES
                    ('01', 'New'),
                    ('02', 'Modify with documents'),
                    ('03', 'Modify without documents'),
                    ('04', 'Dump'),
                    ('05', 'Suspended'),
                    ('06', 'Deceased');
            `);

    await queryRunner.query(`CREATE TABLE application_statuses (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    application_status_code VARCHAR(10),
                    application_status_description VARCHAR(100)
                );
            `);

    await queryRunner.query(`INSERT INTO application_statuses (application_status_code, application_status_description) VALUES
                ('R', 'Resident Indian'),
                ('N', 'Non-Resident Indian'),
                ('P', 'Foreign National'),
                ('I', 'Person of Indian Origin');
            `);

    await queryRunner.query(`CREATE TABLE address_types (
                id INT AUTO_INCREMENT PRIMARY KEY,
                code VARCHAR(10),
                communication_address_type VARCHAR(100)
            );`);

    await queryRunner.query(`INSERT INTO address_types (code, communication_address_type) VALUES
                    ('01', 'Residential/Business'),
                    ('02', 'Residential'),
                    ('03', 'Business'),
                    ('04', 'Registered office'),
                    ('05', 'Unspecified');
                    `);

    await queryRunner.query(`CREATE TABLE income_ranges (
                id INT AUTO_INCREMENT PRIMARY KEY,
                income_range VARCHAR(50),
                income_range_identifier VARCHAR(150),
                code VARCHAR(10)
            );
            `);

    await queryRunner.query(`INSERT INTO income_ranges (income_range,income_range_identifier, code) VALUES
                ('Below 1 Lac','upto_1lakh', '31'),
                ('1-5 Lacs','above_1lakh_upto_5lakh', '32'),
                ('5-10 Lacs','above_5lakh_upto_10lakh' ,'33'),
                ('10-25 Lacs','above_10lakh_upto_25lakh', '34'),
                ('25 Lacs-1 crore','above_25lakh_upto_1cr','35'),
                ('1 crore','above_1cr','36');
            `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
