import { MigrationInterface, QueryRunner } from 'typeorm';

export class KfintechInvestorMasterFolios1725443931093
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE kfintech_transaction_master_folios (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            user_id INT NULL,
            product_code VARCHAR(100),
            fund VARCHAR(100),
            scheme VARCHAR(100),
            plan VARCHAR(100),
            folio_number VARCHAR(100),
            scheme_code VARCHAR(100),
            dividend_option VARCHAR(50),
            fund_description VARCHAR(200),
            transaction_head VARCHAR(50),
            transaction_number INT,
            switch_ref_no VARCHAR(100),
            instrument_number VARCHAR(100),
            investor_name VARCHAR(100),
            transaction_mode VARCHAR(100),
            transaction_status VARCHAR(50),
            branch_name VARCHAR(100),
            branch_transaction_no INT,
            transaction_date DATE,
            process_date DATE,
            units FLOAT,
            amount DECIMAL(15, 2),
            agent_code VARCHAR(100),
            sub_broker_code VARCHAR(100),
            brokerage_percentage DECIMAL(5, 2),
            commission DECIMAL(15, 2),
            investor_id VARCHAR(100),
            report_date DATE,
            report_time TIME,
            transaction_sub VARCHAR(100),
            application_number VARCHAR(100),
            transaction_id VARCHAR(100),
            transaction_description VARCHAR(255),
            transaction_type VARCHAR(100),
            nav_date DATE,
            port_date DATE,
            asset_type VARCHAR(100),
            sub_tran_type VARCHAR(100),
            city_category VARCHAR(100),
            euin VARCHAR(100),
            tr_charges DECIMAL(15, 2),
            client_id VARCHAR(100),
            dp_id VARCHAR(100),
            stt DECIMAL(15, 2),
            ih_no VARCHAR(100),
            branch_code VARCHAR(100),
            inward_number VARCHAR(100),
            pan1 VARCHAR(20),
            pan2 VARCHAR(20),
            pan3 VARCHAR(20),
            tds_amount DECIMAL(15, 2),
            instrument_date DATE,
            instrument_bank VARCHAR(100),
            transaction_flag VARCHAR(50),
            load_amount DECIMAL(15, 2),
            nct_change_date DATE,
            remarks TEXT,
            to_product_code VARCHAR(100),
            status VARCHAR(50),
            isin VARCHAR(100),
            nav DECIMAL(15, 8),
            ins_amount DECIMAL(15, 2),
            rej_trno_org_no VARCHAR(100),
            euin_valid_indicator VARCHAR(50),
            euin_declaration_indicator VARCHAR(50),
            sub_broker_arn_code VARCHAR(100),
            atm_card_remarks TEXT,
            atm_card_status VARCHAR(100),
            sch1 VARCHAR(100),
            pln1 VARCHAR(100),
            td_trxn_mode VARCHAR(50),
            new_unq_no VARCHAR(100),
            sip_regn_date DATE,
            div_per DECIMAL(5, 2),
            price DECIMAL(15, 8),
            electronic_transaction_flag VARCHAR(50),
            stamp_duty_charges DECIMAL(15, 2),
            is_deleted tinyint default 0,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            \`created_at\` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
            \`updated_at\` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB;
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
