import { MigrationInterface, QueryRunner } from 'typeorm';

export class CamsInvestorMasterFolios1725432539248
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE cams_investor_master_folios (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            user_id INT NULL,
            folio VARCHAR(100),
            inv_name VARCHAR(100),
            address1 VARCHAR(100),
            address2 VARCHAR(100),
            address3 VARCHAR(100),
            city VARCHAR(100),
            pincode VARCHAR(50),
            product VARCHAR(200),
            sch_name VARCHAR(100),
            rep_date DATE,
            clos_bal FLOAT,
            rupee_bal FLOAT,
            jnt_name1 VARCHAR(100),
            jnt_name2 VARCHAR(100),
            phone_off VARCHAR(20),
            phone_res VARCHAR(20),
            email VARCHAR(100),
            holding_nature VARCHAR(100),
            uin_no VARCHAR(100),
            pan_no VARCHAR(20),
            joint1_pan VARCHAR(100),
            joint2_pan VARCHAR(100),
            guard_pan VARCHAR(100),
            tax_status VARCHAR(100),
            broker_code VARCHAR(100),
            subbroker VARCHAR(100),
            reinv_flag VARCHAR(50),  
            bank_name VARCHAR(100),
            branch VARCHAR(100),
            ac_type VARCHAR(100),
            ac_no VARCHAR(100),
            b_address1 VARCHAR(100),
            b_address2 VARCHAR(100),
            b_address3 VARCHAR(100),
            b_city VARCHAR(100),
            b_pincode VARCHAR(50),
            inv_dob DATE,
            mobile_no VARCHAR(20),
            occupation VARCHAR(100),
            inv_iin VARCHAR(100),
            nom_name VARCHAR(100),
            relation VARCHAR(100),
            nom_addr1 VARCHAR(100),
            nom_addr2 VARCHAR(100),
            nom_addr3 VARCHAR(100),
            nom_city VARCHAR(100),
            nom_state VARCHAR(100),
            nom_pincode VARCHAR(20),
            nom_ph_off VARCHAR(100),
            nom_ph_res VARCHAR(100),
            nom_email VARCHAR(100),
            nom_percentage DECIMAL(5, 2),
            nom2_name VARCHAR(100),
            nom2_relation VARCHAR(100),
            nom2_addr1 VARCHAR(100),
            nom2_addr2 VARCHAR(100),
            nom2_addr3 VARCHAR(100),
            nom2_city VARCHAR(100),
            nom2_state VARCHAR(100),
            nom2_pincode VARCHAR(20),
            nom2_ph_off VARCHAR(100),
            nom2_ph_res VARCHAR(100),
            nom2_email VARCHAR(100),
            nom2_percentage DECIMAL(5, 2),
            nom3_name VARCHAR(100),
            nom3_relation VARCHAR(100),
            nom3_addr1 VARCHAR(100),
            nom3_addr2 VARCHAR(100),
            nom3_addr3 VARCHAR(100),
            nom3_city VARCHAR(100),
            nom3_state VARCHAR(100),
            nom3_pincode VARCHAR(20),
            nom3_ph_off VARCHAR(100),
            nom3_ph_res VARCHAR(100),
            nom3_email VARCHAR(100),
            nom3_percentage DECIMAL(5, 2),
            ifsc_code VARCHAR(100),
            dp_id VARCHAR(100),
            demat VARCHAR(100),
            guard_name VARCHAR(100),
            brokcode VARCHAR(100),
            folio_date DATE,
            aadhaar VARCHAR(100),
            tpa_linked VARCHAR(100),
            fh_ckyc_no VARCHAR(100),
            jh1_ckyc VARCHAR(100),
            jh2_ckyc VARCHAR(100),
            g_ckyc_no VARCHAR(100),
            jh1_dob DATE,
            jh2_dob DATE,
            guardian_dob DATE,
            amc_code VARCHAR(100),
            gst_state_code INT,
            folio_old VARCHAR(100),
            scheme_folio_number VARCHAR(100),
            is_deleted tinyint default 0,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            \`created_at\` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
            \`updated_at\` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB;
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}

//id     rep_date
