import { MigrationInterface, QueryRunner } from 'typeorm';

export class KfintechInvestorMasterFolios1725617818334
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE kfintech_investor_master_folios (
            id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            user_id INT NULL,
            product_code VARCHAR(100),
            fund VARCHAR(100),
            folio VARCHAR(100),
            fund_description TEXT,
            investor_name VARCHAR(100),
            joint_name_1 VARCHAR(100),
            joint_name_2 VARCHAR(100),
            address_1 VARCHAR(200),
            address_2 VARCHAR(200),
            address_3 VARCHAR(200),
            city VARCHAR(100),
            pincode VARCHAR(50),
            state VARCHAR(100),
            country VARCHAR(100),
            tpin VARCHAR(50),
            date_of_birth DATE,
            f_name VARCHAR(100),
            m_name VARCHAR(100),
            phone_residence VARCHAR(100),
            phone_res_1 VARCHAR(100),
            phone_res_2 VARCHAR(100),
            phone_office VARCHAR(100),
            phone_off_1 VARCHAR(100),
            phone_off_2 VARCHAR(100),
            fax_residence VARCHAR(100),
            fax_office VARCHAR(100),
            tax_status VARCHAR(50),
            occ_code INT,
            email VARCHAR(100),
            bank_acc_no VARCHAR(100),
            bank_name VARCHAR(100),
            account_type VARCHAR(100),
            branch VARCHAR(100),
            bank_address_1 VARCHAR(200),
            bank_address_2 VARCHAR(200),
            bank_address_3 VARCHAR(200),
            bank_city VARCHAR(100),
            bank_phone VARCHAR(100),
            bank_state VARCHAR(100),
            bank_country VARCHAR(100),
            investor_id VARCHAR(100),
            broker_code VARCHAR(100),
            report_date DATE,
            report_time TIME,
            pan_number VARCHAR(100),
            mobile_number VARCHAR(100),
            dividend_option VARCHAR(100),
            occupation_description VARCHAR(200),
            mode_of_holding_description VARCHAR(100),
            mapin_id VARCHAR(100),
            pan_2 VARCHAR(100),
            pan_3 VARCHAR(100),
            category INT,
            guardian_name VARCHAR(100),
            nominee VARCHAR(100),
            client_id VARCHAR(100),
            dpid VARCHAR(100),
            category_desc VARCHAR(100),
            status_desc VARCHAR(100),
            ifsc_code VARCHAR(100),
            nominee_2 VARCHAR(100),
            nominee_3 VARCHAR(100),
            kyc_1_flag VARCHAR(100),
            kyc_2_flag VARCHAR(100),
            kyc_3_flag VARCHAR(100),
            guard_pan_no VARCHAR(100),
            last_updated_date DATE,
            common_acc_no VARCHAR(100),
            nominee_relation VARCHAR(100),
            nominee_2_relation VARCHAR(100),
            nominee_3_relation VARCHAR(100),
            nominee_ratio INT,
            nominee_2_ratio INT,
            nominee_3_ratio INT,
            holder_1_aadhaar_info VARCHAR(100),
            holder_2_aadhaar_info VARCHAR(100),
            holder_3_aadhaar_info VARCHAR(100),
            guardian_aadhaar_info VARCHAR(100),
            nominee_address_1 VARCHAR(100),
            nominee_address_2 VARCHAR(100),
            nominee_address_3 VARCHAR(100),
            nominee_city VARCHAR(100),
            nominee_state VARCHAR(100),
            nominee_pincode VARCHAR(100),
            nominee_phone_residence VARCHAR(100),
            nominee_email VARCHAR(100),
            nominee_2_address_1 VARCHAR(100),
            nominee_2_address_2 VARCHAR(100),
            nominee_2_address_3 VARCHAR(100),
            nominee_2_city VARCHAR(100),
            nominee_2_state VARCHAR(100),
            nominee_2_pincode VARCHAR(100),
            nominee_2_phone_residence VARCHAR(100),
            nominee_2_email VARCHAR(100),
            nominee_3_address_1 VARCHAR(100),
            nominee_3_address_2 VARCHAR(100),
            nominee_3_address_3 VARCHAR(100),
            nominee_3_city VARCHAR(100),
            nominee_3_state VARCHAR(100),
            nominee_3_pincode VARCHAR(100),
            nominee_3_phone_residence VARCHAR(100),
            nominee_3_email VARCHAR(100),
            ckyc_no VARCHAR(100),
            jh1_ckyc VARCHAR(100),
            jh2_ckyc VARCHAR(100),
            guardian_ckyc_no VARCHAR(100),
            joint_holder_1st_resi_phone_no VARCHAR(100),
            joint_holder_2nd_resi_phone_no VARCHAR(100),
            investors_resi_fax_no VARCHAR(100),
            kyc_g_flag VARCHAR(100),
            demat_folio_flag VARCHAR(50),
            nominee_opt_out_flag VARCHAR(50),
            nominee_dob DATE,
            joint_holder_1_contact_number VARCHAR(100),
            joint_holder_1_email_id VARCHAR(100),
            joint_holder_2_contact_number VARCHAR(100),
            joint_holder_2_email_id VARCHAR(100),
            nominee_guardian_name VARCHAR(100),
            email_concern VARCHAR(50),
            email_relationship VARCHAR(100),
            mobile_relationship VARCHAR(100),
            ubo_flag VARCHAR(50),
            npo_flag VARCHAR(50),
            is_deleted tinyint default 0,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            \`created_at\` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
            \`updated_at\` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB;
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
