import { MigrationInterface, QueryRunner } from 'typeorm';

export class Transactiondetails1729845487348 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE cams_transaction_details (
                id SERIAL PRIMARY KEY,
                amc_code VARCHAR(255),
                folio_no VARCHAR(255),
                prod_code VARCHAR(255),
                scheme VARCHAR(255),
                inv_name VARCHAR(255),
                trxn_type VARCHAR(255),
                trxn_no VARCHAR(255),
                trxn_mode VARCHAR(255),
                trxn_stat VARCHAR(255),
                user_code VARCHAR(255),
                usr_trx_no VARCHAR(255),
                trad_date DATE,
                post_date DATE,
                pur_price DECIMAL(18, 2),
                units DECIMAL(18, 2),
                amount DECIMAL(18, 2),
                brok_code VARCHAR(255),
                sub_brok VARCHAR(255),
                brok_perc DECIMAL(5, 2),
                brok_comm DECIMAL(18, 2),
                alt_folio VARCHAR(255),
                rep_date DATE,
                time1 VARCHAR(255),
                trxn_sub_typ VARCHAR(255),
                applicatio VARCHAR(255),
                trxn_natur VARCHAR(255),
                tax DECIMAL(18, 2),
                total_tax DECIMAL(18, 2),
                te15h VARCHAR(255),
                micr_no VARCHAR(255),
                remarks VARCHAR(255),
                sw_flag VARCHAR(255),
                old_folio VARCHAR(255),
                seq_no BIGINT,
                reinvest_f VARCHAR(255),
                mult_brok VARCHAR(255),
                stt DECIMAL(18, 2),
                location VARCHAR(255),
                scheme_typ VARCHAR(255),
                tax_status VARCHAR(255),
                \`load\` DECIMAL(18, 2), 
                scan_ref_no VARCHAR(255),
                pan VARCHAR(255),
                inv_iin VARCHAR(255),
                targ_src_s VARCHAR(255),
                trxn_type_ VARCHAR(255),
                ticob_trty VARCHAR(255),
                ticob_trno VARCHAR(255),
                ticob_post DATE,
                dp_id VARCHAR(255),
                trxn_charg DECIMAL(18, 2),
                eligib_amt DECIMAL(18, 2),
                src_of_txn VARCHAR(255),
                trxn_suffi VARCHAR(255),
                sip_trxn_no VARCHAR(255),
                ter_locati VARCHAR(255),
                euin VARCHAR(255),
                euin_valid BOOLEAN,
                euin_opted BOOLEAN,
                sub_brk_ar VARCHAR(255),
                exch_dc_fl VARCHAR(255),
                src_brk_co VARCHAR(255),
                sys_regn_d DATE,
                ac_no VARCHAR(255),
                bank_name VARCHAR(255),
                reversal_c VARCHAR(255),
                exchange_f VARCHAR(255),
                ca_initiat VARCHAR(255),
                gst_state_ VARCHAR(255),
                igst_amount DECIMAL(18, 2),
                cgst_amount DECIMAL(18, 2),
                sgst_amount DECIMAL(18, 2),
                rev_remark VARCHAR(255),
                original_t VARCHAR(255),
                stamp_duty DECIMAL(18, 2),
                folio_old VARCHAR(255),
                scheme_fol VARCHAR(255),
                amc_ref_no VARCHAR(255),
                request_re VARCHAR(255)
            )
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
