import { MigrationInterface, QueryRunner } from 'typeorm';

export class InvestorDetails1729575643172 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE investor_details (
             id INT PRIMARY KEY AUTO_INCREMENT,
              user_id INT,
              object VARCHAR(255),
              amc VARCHAR(255),
              number VARCHAR(255),
              dp_id VARCHAR(255),
              client_id VARCHAR(255),
              primary_investor_pan VARCHAR(255),
              secondary_investor_pan VARCHAR(255),
              third_investor_pan VARCHAR(255),
              holding_pattern VARCHAR(50),
              primary_investor_name VARCHAR(255),
              secondary_investor_name VARCHAR(255),
              third_investor_name VARCHAR(255),
              primary_investor_dob DATE,
              secondary_investor_dob DATE,
              third_investor_dob DATE,
              primary_investor_gender VARCHAR(10),
              secondary_investor_gender VARCHAR(10),
              third_investor_gender VARCHAR(10),
              primary_investor_tax_status VARCHAR(50),
              primary_investor_occupation VARCHAR(50),
              guardian_name VARCHAR(255),
              guardian_gender VARCHAR(10),
              guardian_pan VARCHAR(255),
              guardian_dob DATE,
              guardian_relationship VARCHAR(255),
              nominee1_name VARCHAR(255),
              nominee1_dob DATE,
              nominee1_relationship VARCHAR(255),
              nominee1_guardian VARCHAR(255),
              nominee1_guardian_dob VARCHAR(255),
              nominee1_allocation_percentage DECIMAL,
              nominee2_name VARCHAR(255),
              nominee2_dob DATE,
              nominee2_relationship VARCHAR(255),
              nominee2_guardian VARCHAR(255),
              nominee2_guardian_dob VARCHAR(255),
              nominee2_allocation_percentage DECIMAL,
              nominee3_name VARCHAR(255),
              nominee3_dob DATE,
              nominee3_relationship VARCHAR(255),
              nominee3_guardian VARCHAR(255),
              nominee3_guardian_dob VARCHAR(255),
              nominee3_allocation_percentage DECIMAL,
              scheme VARCHAR(255),
              scheme_code VARCHAR(255),
              bank_account_name VARCHAR(255),
              bank_account_number VARCHAR(255),
              bank_account_type VARCHAR(50),
              bank_account_ifsc VARCHAR(255),
              address_line1 VARCHAR(255),
              address_line2 VARCHAR(255),
              address_line3 VARCHAR(255),
              city VARCHAR(255),
              state VARCHAR(255),
              postal_code VARCHAR(10),
              country_name VARCHAR(255),
              country_ansi_code VARCHAR(10),
              email_address TEXT,
              mobile_number TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
              FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            );
          `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
