import { MigrationInterface, QueryRunner } from 'typeorm';

export class Createnewtabletransactionmasterfolios1731069125470
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE kfintech_transaction_master_folios (
              id INT AUTO_INCREMENT PRIMARY KEY,
              FMCODE VARCHAR(50),
              TD_FUND VARCHAR(50),
              TD_ACNO VARCHAR(50),
              SCHPLN VARCHAR(50),
              FUNDDESC VARCHAR(255),
              TD_PURRED VARCHAR(50),
              TD_TRNO VARCHAR(50),
              SMCODE VARCHAR(50),
              CHQNO VARCHAR(50),
              INVNAME VARCHAR(255),
              TRNMODE VARCHAR(50),
              TRNSTAT VARCHAR(50),
              TD_BRANCH VARCHAR(50),
              ISCTRNO VARCHAR(50),
              TD_TRDT DATE,
              TD_PRDT DATE,
              TD_POP DECIMAL(10, 2),
              TD_UNITS DECIMAL(10, 2),
              TD_AMT DECIMAL(15, 2),
              TD_AGENT VARCHAR(50),
              TD_BROKER VARCHAR(50),
              BROKPER DECIMAL(5, 2),
              BROKCOMM DECIMAL(15, 2),
              INVID VARCHAR(50),
              CRDATE DATE,
              CRTIME VARCHAR(50),
              TRNSUB VARCHAR(50),
              TD_APPNO VARCHAR(50),
              UNQNO VARCHAR(50),
              TRDESC VARCHAR(255),
              TD_TRTYPE VARCHAR(50),
              CHQDATE DATE,
              CHQBANK VARCHAR(255),
              DIVOPT VARCHAR(50),
              TRFLAG VARCHAR(50),
              TD_NAV DECIMAL(15, 4),
              STT DECIMAL(15, 2),
              LOAD1 DECIMAL(15, 2),
              IHNO VARCHAR(50),
              BRANCHCODE VARCHAR(50),
              INWARDNUM0 VARCHAR(50),
              PAN1 VARCHAR(50),
              NCTREMARKS VARCHAR(255),
              NAVDATE DATE,
              PAN2 VARCHAR(50),
              PAN3 VARCHAR(50),
              TDSAMOUNT DECIMAL(15, 2),
              SCH1 VARCHAR(50),
              PLN1 VARCHAR(50),
              PRCODE1 VARCHAR(50),
              TD_TRXNMO1 VARCHAR(50),
              CLIENTID VARCHAR(50),
              DPID VARCHAR(50),
              STATUS VARCHAR(50),
              REJTRNOOR2 VARCHAR(50),
              SUBTRTYPE VARCHAR(50),
              TRCHARGES DECIMAL(15, 2),
              ATMCARDST3 VARCHAR(50),
              ATMCARDRE4 VARCHAR(50),
              BROK_ENTDT DATE,
              SCHEMEISIN VARCHAR(50),
              CITYCATEG5 VARCHAR(50),
              PORTDT DATE,
              NEWUNQNO VARCHAR(50),
              EUIN VARCHAR(50),
              SUBARNCODE VARCHAR(50),
              EVALID VARCHAR(50),
              EDECLFLAG BOOLEAN,
              ASSETTYPE VARCHAR(50),
              SIPREGDT DATE,
              TD_SCHEME VARCHAR(50),
              TD_PLAN VARCHAR(50),
              INSAMOUNT DECIMAL(15, 2),
              BROK_VALU6 DECIMAL(15, 2),
              DIVPER DECIMAL(5, 2),
              CAN VARCHAR(50),
              EXCHORGTR7 VARCHAR(50),
              ELECTRXNF8 VARCHAR(50),
              SIPREGSLNO VARCHAR(50),
              CLEARED BOOLEAN,
              INVSTATE VARCHAR(50),
              STAMPDUTY DECIMAL(15, 2),
              FEEDTYPE VARCHAR(50)
            );
          `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
