import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddBseV1BankCode1736746640306 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS bsev1_emandate_bank_code (
        id SERIAL PRIMARY KEY,
        pay_mode VARCHAR(20),
        bank_name VARCHAR(255),
        bank_id VARCHAR(20),
        merged_bank_id VARCHAR(20) DEFAULT NULL
      )
    `);

    // Insert the data
    await queryRunner.query(`
      INSERT INTO bsev1_emandate_bank_code (pay_mode, bank_name, bank_id, merged_bank_id)
      VALUES
        ('DIRECT', 'Kotak Mahindra Bank', '162', NULL),
        ('DIRECT', 'HDFC Bank Limited', 'HDF', NULL),
        ('DIRECT', 'ICICI Bank', 'ICI', NULL),
        ('DIRECT', 'State Bank of India', 'SBI', NULL),
        ('DIRECT', 'Axis Bank', 'UTI', NULL),
        ('DIRECT', 'YES Bank', 'YBK', NULL),
        ('DIRECT', 'IndusInd Bank', 'IDS', NULL),
        ('NODAL', 'Andhra Bank', 'ADB', 'UBI'),
        ('NODAL', 'Andhra Bank Corporate', 'ADC', NULL),
        ('NODAL', 'Allahabad Bank', 'ALB', 'INB'),
        ('NODAL', 'Allahabad Bank Corporate', 'ALC', NULL),
        ('NODAL', 'Andhra Pragathi Grameena Bank', 'APG', NULL),
        ('NODAL', 'AU Small Finance Bank', 'AUB', NULL),
        ('NODAL', 'Axis Bank Corporate', 'AXC', NULL),
        ('NODAL', 'Bank of Baroda-Corporate', 'BBC', NULL),
        ('NODAL', 'Bank of Bahrain and Kuwait', 'BBK', NULL),
        ('NODAL', 'Bank of Baroda- Retail', 'BBR', NULL),
        ('NODAL', 'Bassein Catholic Bank', 'BCB', NULL),
        ('NODAL', 'Bandhan Bank Corporate', 'BDC', NULL),
        ('NODAL', 'Bandhan Bank', 'BDN', NULL),
        ('NODAL', 'Bank Of India', 'BOI', NULL),
        ('NODAL', 'Bank of Maharashtra', 'BOM', NULL),
        ('NODAL', 'Central Bank of India', 'CBI', NULL),
        ('NODAL', 'Canara Bank', 'CNB', NULL),
        ('NODAL', 'Capital Bank', 'CPB', NULL),
        ('NODAL', 'Cosmos Bank', 'COB', NULL),
        ('NODAL', 'Corporate Punjab National Bank', 'CPN', NULL),
        ('NODAL', 'Corporation Bank Corporate', 'CR2', NULL),
        ('NODAL', 'Corporation Bank', 'CRP', 'UBI'),
        ('NODAL', 'Catholic Syrian Bank', 'CSB', NULL),
        ('NODAL', 'City Union Bank', 'CUB', NULL),
        ('NODAL', 'Deutsche Bank', 'DBK', NULL),
        ('NODAL', 'DIGI Bank', 'DBS', NULL),
        ('NODAL', 'Development Credit Bank', 'DCB', NULL),
        ('NODAL', 'Dena Bank Net Banking', 'DEN', 'BBR'),
        ('NODAL', 'Dhanlakshmi Bank Corporate', 'DL2', NULL),
        ('NODAL', 'Dhanlakshmi Bank', 'DLB', NULL),
        ('NODAL', 'Equitas Bank', 'EQB', NULL),
        ('NODAL', 'ESAF Small Finance Bank', 'ESF', NULL),
        ('NODAL', 'Federal Bank', 'FBK', NULL),
        ('NODAL', 'Fincare Small Finance Bank', 'FNC', NULL),
        ('NODAL', 'HDFC UPI', 'HD4', NULL),
        ('NODAL', 'Gujarat State Cooperative Bank', 'GSB', NULL),
        ('NODAL', 'HSBC', 'HSB', NULL),
        ('NODAL', 'UPI', 'IC4', NULL),
        ('NODAL', 'IDBI Bank', 'IDB', NULL),
        ('NODAL', 'IDBI Bank Corporate', 'IDC', NULL),
        ('NODAL', 'IDFC Bank Netbanking', 'IDN', NULL),
        ('NODAL', 'Indian Bank', 'INB', NULL),
        ('NODAL', 'Indian Overseas Bank', 'IOB', NULL),
        ('NODAL', 'Jammu & Kashmir Bank Limited', 'JKB', NULL),
        ('NODAL', 'Jana Small Finance Bank', 'JNB', NULL),
        ('NODAL', 'Janata Sahakari Bank', 'JSB', NULL),
        ('NODAL', 'Karnataka Bank', 'KBL', NULL),
        ('NODAL', 'Kalupur Coop Bank', 'KLB', NULL),
        ('NODAL', 'Karur Vysya Bank Limited', 'KVB', NULL),
        ('NODAL', 'Karnataka Vikas Gramin Bank', 'KVG', NULL),
        ('NODAL', 'Lakshmi Vilas Bank Corporate', 'LVC', NULL),
        ('NODAL', 'Lakshmi Vilas Bank Retail', 'LVR', NULL),
        ('NODAL', 'Maharashtra Gramin Bank', 'MGB', NULL),
        ('NODAL', 'North East Small Finance Bank', 'NEB', NULL),
        ('NODAL', 'NKGSB Bank', 'NKB', NULL),
        ('NODAL', 'Nutan Nagarik Sahakari Bank', 'NUT', NULL),
        ('NODAL', 'ORIENTAL BANK OF COMMERCE', 'OBC', 'PNB'),
        ('NODAL', 'Pragathi Krishna Bank', 'PKB', NULL),
        ('NODAL', 'Punjab National Bank', 'PNB', NULL),
        ('NODAL', 'Punjab and Sind Bank', 'PSB', NULL),
        ('NODAL', 'Ratnakar Bank', 'RBL', NULL),
        ('NODAL', 'RBL Bank Coporate', 'RTC', NULL),
        ('NODAL', 'SCB Net Banking', 'SCB', NULL),
        ('NODAL', 'South Indian Bank Ltd', 'SIB', NULL),
        ('NODAL', 'SBM Bank', 'SOM', NULL),
        ('NODAL', 'Suryoday Small Finance Bank', 'SRB', NULL),
        ('NODAL', 'Surat Bank', 'SUR', NULL),
        ('NODAL', 'Sutex Bank', 'SUT', NULL),
        ('NODAL', 'Shamrao Vithal Bank Corporate', 'SV2', NULL),
        ('NODAL', 'Shamrao Vithal Co.Operative Bank Ltd', 'SVC', NULL),
        ('NODAL', 'Saraswat Bank', 'SWB', NULL),
        ('NODAL', 'Syndicate Bank', 'SYD', 'CNB'),
        ('NODAL', 'Thane Bharat Sahakari Bank', 'TBB', NULL),
        ('NODAL', 'TJSB', 'TJB', NULL),
        ('NODAL', 'Tamilnad Mercantile Bank Ltd', 'TMB', NULL),
        ('NODAL', 'TNSC Bank', 'TNC', NULL),
        ('NODAL', 'Union Bank of India', 'UBI', NULL),
        ('NODAL', 'Union Bank of India Corporate', 'UB2', NULL),
        ('NODAL', 'UCO Bank', 'UCO', NULL),
        ('NODAL', 'United Bank of India', 'UNI', 'PNB'),
        ('NODAL', 'Ujjivan Bank', 'UJV', NULL),
        ('NODAL', 'Utkarsh Bank', 'UTK', NULL),
        ('NODAL', 'Vijaya Bank', 'VJB', 'BBR'),
        ('NODAL', 'Varachaa Bank', 'VRB', NULL),
        ('NODAL', 'YES Bank Corporate', 'YBC', NULL),
        ('NODAL', 'The Zoroastrian Co-op Bank', 'ZOB', NULL);
    `);

    await queryRunner.query(`
            CREATE TABLE bsev1_upi_banks_code (
                id SERIAL PRIMARY KEY,
                pay_mode VARCHAR(50) NOT NULL,
                bank_name VARCHAR(255) NOT NULL,
                bank_code VARCHAR(50) NOT NULL
            );
        `);

    await queryRunner.query(`
            INSERT INTO bsev1_upi_banks_code (pay_mode, bank_name, bank_code) VALUES
            ('UPI', 'ABHYUDAYA COOPERATIVE BANK LIMITED', 'ACB'),
            ('UPI', 'ADITYA BIRLA IDEA PAYMENTS BANK LTD', 'ABPB'),
            ('UPI', 'AIRTEL PAYMENTS BANK LIMITED', 'AIRP'),
            ('UPI', 'ALLAHABAD BANK', 'ALD'),
            ('UPI', 'IDFC BANK LIMITED', 'IDF'),
            ('UPI', 'Indian Bank', 'INB'),
            ('UPI', 'Indian Overseas Bank', 'IOB'),
            ('UPI', 'IndusInd Bank', 'IDS'),
            ('UPI', 'JALGAON JANATA SAHAKARI BANK LIMITED', 'JJS'),
            ('UPI', 'Jammu & Kashmir Bank', 'JKB'),
            ('UPI', 'Janata Sahakari Bank', 'JSB'),
            ('UPI', 'JIO PAYMENTS BANK LIMITED', 'JIOP'),
            ('UPI', 'KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BANK LIMITED', 'KAI'),
            ('UPI', 'KALYAN JANATA SAHAKARI BANK', 'KJS'),
            ('UPI', 'KAPOL COOPERATIVE BANK LIMITED', 'KCB'),
            ('UPI', 'Karnataka Bank Ltd', 'KBL'),
            ('UPI', 'KARNATAKA VIKAS GRAMEENA BANK', 'KVG'),
            ('UPI', 'Karur Vysya Bank', 'KVB'),
            ('UPI', 'KERALA GRAMIN BANK', 'KLG'),
            ('UPI', 'Kotak Bank', '162'),
            ('UPI', 'Lakshmi Vilas Bank', 'LVB'),
            ('UPI', 'Laxmi Vilas Bank - Corporate Net Banking', 'LVC'),
            ('UPI', 'Laxmi Vilas Bank - Retail Net Banking', 'LVR'),
            ('UPI', 'MAHANAGAR COOPERATIVE BANK', 'MCB'),
            ('UPI', 'MAHARASHTRA GRAMIN BANK', 'MGBX'),
            ('UPI', 'NKGSB BANK', 'NKB'),
            ('UPI', 'Oriental Bank of Commerce', 'OBC'),
            ('UPI', 'PAYTM PAYMENTS BANK LTD', 'PYTM'),
            ('UPI', 'PRAGATHI KRISHNA GRAMIN BANK', 'PKG'),
            ('UPI', 'PRATHAMA BANK', 'PRT'),
            ('UPI', 'Punjab & Maharastra Coop Bank', 'PMC'),
            ('UPI', 'Punjab & Sind Bank', 'PSB'),
            ('UPI', 'Punjab National Bank - Corporate Banking', 'CPN'),
            ('UPI', 'Punjab National Bank - Retail Net Banking', 'PNB'),
            ('UPI', 'RAJKOT NAGRIK SAHAKARI BANK LIMITED', 'RNS'),
            ('UPI', 'Ratnakar Bank - Retail Net Banking', 'RBL'),
            ('UPI', 'RBL Bank Limited', 'RAT'),
            ('UPI', 'Saraswat Bank', 'SWB'),
            ('UPI', 'SHAMRAO VITHAL BANK CORPORATE', 'SV2'),
            ('UPI', 'South Indian Bank', 'SIB'),
            ('UPI', 'Standard Chartered Bank', 'SCB'),
            ('UPI', 'State Bank of India', 'SBI'),
            ('UPI', 'SUTEX COOPERATIVE BANK LIMITED', 'SUT'),
            ('UPI', 'Syndicate Bank', 'SYD'),
            ('UPI', 'Tamilnad Mercantile Bank Ltd.', 'TMB'),
            ('UPI', 'TELANGANA STATE COOP APEX BANK', 'TSA'),
            ('UPI', 'Allahabad Bank - Retail Net Banking', 'ALB'),
            ('UPI', 'ALLAHABAD BANK CORPORATE', 'ALC'),
            ('UPI', 'Andhra Bank', 'ADB'),
            ('UPI', 'ANDHRA PRADESH GRAMEENA VIKAS BANK', 'APGX'),
            ('UPI', 'ANDHRA PRAGATHI GRAMEENA BANK', 'APG'),
            ('UPI', 'APNA SAHAKARI BANK LIMITED', 'ASB'),
            ('UPI', 'AU SMALL FINANCE BANK', 'AUB'),
            ('UPI', 'Axis Bank', 'UTI'),
            ('UPI', 'BANDHAN BANK LIMITED', 'BDB'),
            ('UPI', 'Bank of Baroda - Corporate Banking', 'BBC'),
            ('UPI', 'Bank of Baroda - Retail Net Banking', 'BBR'),
            ('UPI', 'Bank Of India', 'BOI'),
            ('UPI', 'Bank of Maharashtra', 'BOM'),
            ('UPI', 'BASSEIN CATHOLIC COOPERATIVE BANK LIMITED', 'BAC'),
            ('UPI', 'Canara Bank', 'CNB'),
            ('UPI', 'Catholic Syrian Bank', 'CSB'),
            ('UPI', 'Central Bank of India', 'CBI'),
            ('UPI', 'CITI BANK', 'CIT'),
            ('UPI', 'CITY UNION BANK LIMITED', 'CUB'),
            ('UPI', 'Corporation Bank', 'CRP'),
            ('UPI', 'DCB BANK LIMITED', 'DCB'),
            ('UPI', 'Dena Bank', 'DEN'),
            ('UPI', 'DEVELOPMENT BANK OF SINGAPORE', 'DBS'),
            ('UPI', 'Dhanlakshmi Bank', 'DLB'),
            ('UPI', 'DOMBIVLI NAGARI SAHAKARI BANK LIMITED', 'DNS'),
            ('UPI', 'Equitas Small Finance Bank Ltd', 'ESF'),
            ('UPI', 'Federal Bank', 'FBK'),
            ('UPI', 'FINO PAYMENTS BANK LTD', 'FINO'),
            ('UPI', 'G P PARSIK BANK', 'PJS'),
            ('UPI', 'HDFC BANK', 'HDF'),
            ('UPI', 'HSBC BANK', 'HSB'),
            ('UPI', 'ICICI Bank - Retail Net Banking', 'ICI'),
            ('UPI', 'IDBI Bank - Retail Net Banking', 'IDB'),
            ('UPI', 'THE COSMOS CO OPERATIVE BANK LIMITED', 'COS'),
            ('UPI', 'THE GUJARAT STATE COOPERATIVE BANK LIMITED', 'GSC'),
            ('UPI', 'THE HASTI COOP BANK LTD', 'HCB'),
            ('UPI', 'THE MEHSANA URBAN COOPERATIVE BANK', 'MSN'),
            ('UPI', 'THE NAINITAL BANK LIMITED', 'NTB'),
            ('UPI', 'THE NAV JEEVAN CO-OP BANK LTD.', 'NJCX'),
            ('UPI', 'THE SHAMRAO VITHAL COOPERATIVE BANK', 'SVC'),
            ('UPI', 'THE SURAT PEOPLES COOPERATIVE BANK LIMITED', 'SPC'),
            ('UPI', 'THE TAMIL NADU STATE APEX COOPERATIVE BANK', 'TNS'),
            ('UPI', 'THE THANE BHARAT SAHAKARI BANK LIMITED', 'TBS'),
            ('UPI', 'THE VARACHHA COOPERATIVE BANK LIMITED', 'VAR'),
            ('UPI', 'THE VIJAY CO OPERATIVE BANK LTD.', 'VIJX'),
            ('UPI', 'THE VISHWESHWAR SAHAKARI BANK LIMITED', 'VSB'),
            ('UPI', 'TJSB Bank', 'TJB'),
            ('UPI', 'TJSB SAHAKARI BANK LTD', 'TJS'),
            ('UPI','UCO Bank', 'UCO'),
            ('UPI','Ujjivan Small Finance Bank Limited', 'UJV'),
            ('UPI','Union Bank of India', 'UBI'),
            ('UPI','United Bank of India', 'UNI'),
            ('UPI','VASAI VIKAS SAHAKARI BANK LIMITED ', 'VVS'),
            ('UPI','Vijaya Bank', 'VJB')
            `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
