import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateOrderTable1738132136356 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS bse_xsip_order (
            id INT AUTO_INCREMENT PRIMARY KEY,
            transaction_code VARCHAR(100),
            unique_reference_no VARCHAR(255),
            scheme_code VARCHAR(255),
            member_id VARCHAR(255),
            client_code VARCHAR(255),
            user_id VARCHAR(255),
            int_ref_no VARCHAR(255),
            transaction_mode VARCHAR(100),
            dp_trans_mode VARCHAR(100),
            start_date VARCHAR(100),
            frequency_type VARCHAR(255),
            frequency_allowed int,
            installment_amount DECIMAL(10, 2),
            no_of_installments int,
            remarks VARCHAR(255),
            folio_no VARCHAR(255),
            first_order_flag VARCHAR(100),
            brokerage DECIMAL(10, 2),
            mandate_id BIGINT,
            sub_br_code VARCHAR(255),
            euin VARCHAR(255),
            euin_flag VARCHAR(100),
            dpc VARCHAR(100),
            xsip_reg_id int,
            ip_add VARCHAR(255),
            password VARCHAR(255),
            passKey VARCHAR(255),
            param1 VARCHAR(255),
            param2 VARCHAR(255),
            param3 VARCHAR(255),
            filler1 VARCHAR(255),
            filler2 VARCHAR(255),
            filler3 VARCHAR(255),
            filler4 VARCHAR(255),
            filler5 VARCHAR(255),
            filler6 VARCHAR(255),
            bse_remarks VARCHAR(1000),
            success_flag VARCHAR(100),
            transaction_basket_item_id INT,
            FOREIGN KEY (transaction_basket_item_id) REFERENCES transaction_basket_items(id) ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        );`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS bse_purchase_redemption_order (
            id INT AUTO_INCREMENT PRIMARY KEY,
            type VARCHAR(100),
            transaction_code VARCHAR(100),
            transaction_no VARCHAR(255),
            order_id bigint,
            user_id bigint,
            member_id VARCHAR(255),
            client_code VARCHAR(255),
            scheme_code VARCHAR(255),
            buy_sell VARCHAR(100),
            buy_sell_type VARCHAR(100),
            dp_trans_mode VARCHAR(100),
            amount DECIMAL(10, 2),
            qty DECIMAL(10, 2),
            all_redeem VARCHAR(100),
            folio_no VARCHAR(255),
            remarks VARCHAR(255),
            kyc_status VARCHAR(255),
            int_ref_no VARCHAR(255),
            sub_br_code VARCHAR(255),
            euin VARCHAR(255),
            euin_flag VARCHAR(100),
            min_redeem VARCHAR(100),
            dpc VARCHAR(100),
            ip_add VARCHAR(255),
            password VARCHAR(255),
            passKey VARCHAR(255),
            param1 VARCHAR(255),
            param2 VARCHAR(255),
            param3 VARCHAR(255),
            mobile_no VARCHAR(255),
            email VARCHAR(255),
            mandate_id VARCHAR(255),
            filler1 VARCHAR(255),
            filler2 VARCHAR(255),
            filler3 VARCHAR(255),
            filler4 VARCHAR(255),
            filler5 VARCHAR(255),
            filler6 VARCHAR(255),
            order_no bigint,
            bse_remarks VARCHAR(1000),
            success_flag VARCHAR(100),
            transaction_basket_item_id INT,
            FOREIGN KEY (transaction_basket_item_id) REFERENCES transaction_basket_items(id) ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        );`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS bse_switch_order (
            id INT AUTO_INCREMENT PRIMARY KEY,
            type VARCHAR(100),
            transaction_code VARCHAR(100),
            unique_reference_no VARCHAR(255),
            order_id bigint,
            user_id bigint,
            member_id VARCHAR(255),
            client_code VARCHAR(255),
            from_scheme_code VARCHAR(255),
            to_scheme_code VARCHAR(255),
            buy_sell VARCHAR(100),
            buy_sell_type VARCHAR(100),
            dp_trans_mode VARCHAR(100),
            int_ref_no VARCHAR(255),
            switch_amount DECIMAL(10, 2),
            switch_units DECIMAL(10, 2),
            all_units_flag VARCHAR(100),
            folio_no VARCHAR(255),
            remarks VARCHAR(255),
            kyc_status VARCHAR(255),
            sub_br_code VARCHAR(255),
            euin VARCHAR(255),
            euin_flag VARCHAR(100),
            min_redeem VARCHAR(100),
            ip_add VARCHAR(255),
            password VARCHAR(255),
            passKey VARCHAR(255),
            param1 VARCHAR(255),
            param2 VARCHAR(255),
            param3 VARCHAR(255),
            filler1 VARCHAR(255),
            filler2 VARCHAR(255),
            filler3 VARCHAR(255),
            filler4 VARCHAR(255),
            filler5 VARCHAR(255),
            filler6 VARCHAR(255),
            order_no bigint,
            bse_remarks VARCHAR(1000),
            success_flag VARCHAR(100),
            transaction_basket_item_id INT,
            FOREIGN KEY (transaction_basket_item_id) REFERENCES transaction_basket_items(id) ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        );`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
